# Generated by Django 2.0.8 on 2019-01-12 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('short_name', models.CharField(max_length=10, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('mobile', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=50)),
                ('address', models.TextField(blank=True, max_length=300)),
                ('gst_no', models.CharField(max_length=30, null=True)),
                ('cst_no', models.CharField(max_length=30, null=True)),
                ('tin_no', models.CharField(max_length=30, null=True)),
                ('pan_no', models.CharField(max_length=10, null=True)),
                ('bank_name', models.TextField(blank=True, max_length=50)),
                ('account_holder_name', models.TextField(max_length=50)),
                ('account_no', models.CharField(blank=True, max_length=25, null=True)),
                ('ifsc_code', models.TextField(blank=True, max_length=30, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Company_Created_By_User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Currency_Created_By_User', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Currency_Modified_By_User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('primary_contact_no', models.CharField(max_length=50)),
                ('email_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_person_contact_no', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_person_email_id', models.EmailField(blank=True, max_length=50, null=True)),
                ('secondary_contact_no', models.CharField(blank=True, max_length=50, null=True)),
                ('secondary_email_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('referred_by', models.IntegerField(default=False)),
                ('address', models.CharField(max_length=200)),
                ('max_credit_amount', models.IntegerField(default=0)),
                ('credit_days', models.IntegerField(default=0)),
                ('credit_status', models.CharField(max_length=30)),
                ('billing_address', models.CharField(max_length=200)),
                ('shiping_address', models.CharField(max_length=200)),
                ('gst_no', models.CharField(blank=True, max_length=20, null=True)),
                ('default_cash_customer', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printerapp.Company')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Customer_Created_By_User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='CustomerGroup_Created_By_User', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='CustomerGroup_Modified_By_User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Roletype_Created_By_User', to=settings.AUTH_USER_MODEL)),
                ('emp_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='empname', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Roletype_Modified_By_User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gsm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gsm_name', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Gsm_Created_By_User', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Gsm_Modified_By_User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_name', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Paper_Created_By_User', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Paper_Modified_By_User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.CharField(max_length=50)),
                ('is_deliveryTime', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Process_Created_By_User', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Process_Modified_By_User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Product_Created_By_User', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Product_Modified_By_User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Productdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_gsm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pd_size', to='printerapp.Gsm')),
                ('product_paper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pd_paper', to='printerapp.Paper')),
                ('product_process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pd_process', to='printerapp.Process')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Role_Created_By_User', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Role_Modified_By_User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Size_Created_By_User', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Size_Modified_By_User', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('can_view_odd_ids', 'can_view_odd_ids'), ('can_view_even_ids', 'can_view_even_ids')),
            },
        ),
        migrations.CreateModel(
            name='StateMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50)),
                ('state_code', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='StateMaster_Created_By_User', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='StateMaster_Modified_By_User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='productdetails',
            name='product_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pd_size', to='printerapp.Size'),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='productid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pd_productid', to='printerapp.Product'),
        ),
        migrations.AddField(
            model_name='employee',
            name='role_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Roletype', to='printerapp.Role'),
        ),
        migrations.AddField(
            model_name='customer',
            name='customergroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printerapp.CustomerGroup'),
        ),
        migrations.AddField(
            model_name='customer',
            name='modified_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Customer_Modified_By_User', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_State', to='printerapp.StateMaster'),
        ),
        migrations.AddField(
            model_name='company',
            name='default_currency',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Company_Currency', to='printerapp.Currency'),
        ),
        migrations.AddField(
            model_name='company',
            name='modified_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Company_Modified_By_User', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='Company_State', to='printerapp.StateMaster'),
        ),
        migrations.AlterUniqueTogether(
            name='statemaster',
            unique_together={('state', 'state_code', 'deleted')},
        ),
        migrations.AlterUniqueTogether(
            name='size',
            unique_together={('size_name',)},
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('role_name',)},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('product_name',)},
        ),
        migrations.AlterUniqueTogether(
            name='process',
            unique_together={('process_name',)},
        ),
        migrations.AlterUniqueTogether(
            name='paper',
            unique_together={('paper_name',)},
        ),
        migrations.AlterUniqueTogether(
            name='gsm',
            unique_together={('gsm_name',)},
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('emp_id',)},
        ),
        migrations.AlterUniqueTogether(
            name='customergroup',
            unique_together={('name', 'deleted')},
        ),
        migrations.AlterUniqueTogether(
            name='currency',
            unique_together={('name', 'country', 'deleted')},
        ),
        migrations.AlterUniqueTogether(
            name='company',
            unique_together={('name', 'short_name', 'deleted')},
        ),
    ]
